# -*- coding: utf-8 -*-
"""Copy of India's_Population.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AkAXowIQVtkg84eRX1EfZDo_AmzIt3Gp
"""

# Installation
# !pip install -U plotly pandas kaleido numpy

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np

# Data preparation
data = {
    'Age Group': ['0-20 Years', '21-64 Years', '65+ Years'],
    'Population (Millions)': [512, 807, 98],
    'Percentage': [36.1, 57.0, 6.9]
}
df = pd.DataFrame(data)
df['Growth_Trend'] = [2.1, 1.8, 3.5]
df['Urban_Percentage'] = [34, 38, 28]

# HIGH-TECH DARK THEME COLOR PALETTE
COLORS = {
    'bg_primary': '#0A0E27',      # Deep space blue
    'bg_secondary': '#151B3B',    # Darker blue
    'surface': '#1E2749',         # Card surface
    'surface_light': '#2A3359',   # Lighter surface
    'accent_1': '#64B5F6',        # Ice blue
    'accent_2': '#81C784',        # Mint green
    'accent_3': '#FFB74D',        # Amber
    'text_primary': '#E8EAF6',    # Light lavender
    'text_secondary': '#B0B8D4',  # Muted blue-gray
    'grid': '#2C3559',            # Subtle grid
    'border': '#3D4A7A'           # Border color
}

gradient_colors = [
    'rgba(100, 181, 246, 0.3)',   # Ice blue transparent
    'rgba(129, 199, 132, 0.3)',   # Mint transparent
    'rgba(255, 183, 77, 0.3)'     # Amber transparent
]

bar_colors = [COLORS['accent_1'], COLORS['accent_2'], COLORS['accent_3']]

# Create advanced subplot layout
fig = make_subplots(
    rows=3, cols=3,
    subplot_titles=(
        'POPULATION DISTRIBUTION',
        'DEMOGRAPHIC TREND ANALYSIS',
        'AGE GROUP VELOCITY',
        'GROWTH PROJECTIONS (2020-2030)',
        'HIERARCHICAL STRUCTURE',
        'URBAN-RURAL SPLIT',
        'POPULATION DENSITY HEAT',
        'KEY PERFORMANCE INDICATORS',
        'COMPARATIVE METRICS'
    ),
    specs=[
        [{"type": "bar", "colspan": 1}, {"type": "scatter", "colspan": 1}, {"type": "indicator"}],
        [{"type": "scatter", "colspan": 1}, {"type": "sunburst", "colspan": 1}, {"type": "pie"}],
        [{"type": "bar", "colspan": 1}, {"type": "indicator", "colspan": 1}, {"type": "table"}]
    ],
    vertical_spacing=0.12,
    horizontal_spacing=0.10,
    row_heights=[0.33, 0.33, 0.33],
    column_widths=[0.33, 0.33, 0.33]
)

# ===== CHART 1: 3D-Effect Bar Chart with Glow =====
for idx, row in df.iterrows():
    fig.add_trace(
        go.Bar(
            x=[row['Age Group']],
            y=[row['Population (Millions)']],
            name=row['Age Group'],
            marker=dict(
                color=bar_colors[idx],
                line=dict(color=COLORS['border'], width=2),
                opacity=0.9
            ),
            text=f"{row['Percentage']:.1f}%",
            textposition='outside',
            textfont=dict(size=13, color=COLORS['text_primary'], family='Roboto, Arial'),
            hovertemplate=(
                f"<b style='font-size:14px'>{row['Age Group']}</b><br>" +
                f"<span style='color:{bar_colors[idx]}'>●</span> Population: <b>{row['Population (Millions)']}M</b><br>" +
                f"<span style='color:{bar_colors[idx]}'>●</span> Share: <b>{row['Percentage']:.1f}%</b><br>" +
                f"<span style='color:{bar_colors[idx]}'>●</span> Growth: <b>{row['Growth_Trend']}%</b><br>" +
                "<extra></extra>"
            ),
            width=0.5,
            showlegend=False
        ),
        row=1, col=1
    )

# ===== CHART 2: Animated Area Chart =====
x_data = list(range(2015, 2023))
for idx, row in df.iterrows():
    base = row['Population (Millions)']
    y_data = [base * (0.95 + 0.01*i) for i in range(8)]

    fig.add_trace(
        go.Scatter(
            x=x_data,
            y=y_data,
            name=row['Age Group'],
            mode='lines',
            line=dict(width=3, color=bar_colors[idx], shape='spline'),
            fill='tonexty' if idx > 0 else 'tozeroy',
            fillcolor=gradient_colors[idx],
            stackgroup='one',
            hovertemplate=f"<b>{row['Age Group']}</b><br>Year: %{{x}}<br>Pop: %{{y:.0f}}M<extra></extra>"
        ),
        row=1, col=2
    )

# ===== CHART 3: Speed Gauge =====
fig.add_trace(
    go.Indicator(
        mode="gauge+number+delta",
        value=2.1,
        title={'text': "AVG GROWTH RATE<br><span style='font-size:0.7em;color:#B0B8D4'>Annual %</span>",
               'font': {'size': 14, 'color': COLORS['text_primary']}},
        delta={'reference': 1.8, 'increasing': {'color': COLORS['accent_2']}},
        number={'suffix': "%", 'font': {'size': 32, 'color': COLORS['accent_1']}},
        gauge={
            'axis': {'range': [0, 5], 'tickwidth': 2, 'tickcolor': COLORS['grid']},
            'bar': {'color': COLORS['accent_1'], 'thickness': 0.6},
            'bgcolor': COLORS['surface'],
            'borderwidth': 2,
            'bordercolor': COLORS['border'],
            'steps': [
                {'range': [0, 1.5], 'color': COLORS['surface']},
                {'range': [1.5, 3], 'color': COLORS['surface_light']},
                {'range': [3, 5], 'color': '#2A3359'}
            ],
            'threshold': {
                'line': {'color': COLORS['accent_3'], 'width': 3},
                'thickness': 0.8,
                'value': 3.5
            }
        }
    ),
    row=1, col=3
)

# ===== CHART 4: Future Projection with Confidence Bands =====
x_proj = np.arange(2020, 2031)
for idx, row in df.iterrows():
    base = row['Population (Millions)']
    growth = row['Growth_Trend']
    projection = [base * (1 + growth/100)**(year-2022) for year in x_proj]
    upper_band = [p * 1.05 for p in projection]
    lower_band = [p * 0.95 for p in projection]

    # Upper confidence band
    fig.add_trace(
        go.Scatter(
            x=x_proj, y=upper_band,
            mode='lines',
            line=dict(width=0),
            showlegend=False,
            hoverinfo='skip'
        ),
        row=2, col=1
    )

    # Main projection line
    fig.add_trace(
        go.Scatter(
            x=x_proj,
            y=projection,
            name=row['Age Group'],
            mode='lines+markers',
            line=dict(width=3, color=bar_colors[idx], shape='spline'),
            marker=dict(size=7, color=bar_colors[idx], line=dict(width=2, color=COLORS['bg_primary'])),
            fill='tonexty',
            fillcolor=gradient_colors[idx],
            hovertemplate=f"<b>{row['Age Group']}</b><br>%{{x}}: %{{y:.0f}}M<extra></extra>"
        ),
        row=2, col=1
    )

    # Lower confidence band
    fig.add_trace(
        go.Scatter(
            x=x_proj, y=lower_band,
            mode='lines',
            line=dict(width=0),
            fill='tonexty',
            fillcolor=gradient_colors[idx],
            showlegend=False,
            hoverinfo='skip'
        ),
        row=2, col=1
    )

# ===== CHART 5: Enhanced Sunburst =====
sunburst_labels = ['INDIA', '0-20 Years', '21-64 Years', '65+ Years',
                   'Urban 0-20', 'Rural 0-20', 'Urban 21-64', 'Rural 21-64',
                   'Urban 65+', 'Rural 65+']
sunburst_parents = ['', 'INDIA', 'INDIA', 'INDIA',
                    '0-20 Years', '0-20 Years', '21-64 Years', '21-64 Years',
                    '65+ Years', '65+ Years']
sunburst_values = [1417, 512, 807, 98, 174, 338, 307, 500, 27, 71]

fig.add_trace(
    go.Sunburst(
        labels=sunburst_labels,
        parents=sunburst_parents,
        values=sunburst_values,
        branchvalues="total",
        marker=dict(
            colors=['#1E2749', COLORS['accent_1'], COLORS['accent_2'], COLORS['accent_3'],
                    '#5C8BC7', '#4A6FA5', '#6BA368', '#52814F', '#CC9445', '#A37834'],
            line=dict(width=3, color=COLORS['bg_primary'])
        ),
        hovertemplate='<b>%{label}</b><br>%{value}M<br>%{percentParent}<extra></extra>',
        textfont=dict(size=11, color=COLORS['text_primary'], family='Roboto'),
        insidetextorientation='radial'
    ),
    row=2, col=2
)

# ===== CHART 6: Donut Chart for Urban/Rural =====
urban_total = sum([174, 307, 27])
rural_total = sum([338, 500, 71])

fig.add_trace(
    go.Pie(
        labels=['Urban Population', 'Rural Population'],
        values=[urban_total, rural_total],
        hole=0.6,
        marker=dict(
            colors=[COLORS['accent_1'], COLORS['accent_2']],
            line=dict(color=COLORS['bg_primary'], width=3)
        ),
        textfont=dict(size=13, color=COLORS['text_primary']),
        hovertemplate="<b>%{label}</b><br>%{value}M<br>%{percent}<extra></extra>",
        showlegend=False
    ),
    row=2, col=3
)

# ===== CHART 7: Horizontal Bar (Population Density) =====
density_data = {'Category': ['Youth Density', 'Working Age', 'Senior Density'],
                'Score': [512/1417*100, 807/1417*100, 98/1417*100]}

fig.add_trace(
    go.Bar(
        y=density_data['Category'],
        x=density_data['Score'],
        orientation='h',
        marker=dict(
            color=bar_colors,
            line=dict(color=COLORS['border'], width=2)
        ),
        text=[f"{s:.1f}%" for s in density_data['Score']],
        textposition='outside',
        textfont=dict(size=12, color=COLORS['text_primary']),
        hovertemplate="<b>%{y}</b><br>Density: %{x:.1f}%<extra></extra>",
        showlegend=False
    ),
    row=3, col=1
)

# ===== CHART 8: KPI Indicator =====
fig.add_trace(
    go.Indicator(
        mode="number+delta",
        value=1417,
        title={'text': "TOTAL POPULATION<br><span style='font-size:0.7em;color:#B0B8D4'>Millions</span>",
               'font': {'size': 14, 'color': COLORS['text_primary']}},
        delta={'reference': 1380, 'relative': True, 'valueformat': '.1%',
               'increasing': {'color': COLORS['accent_2']},
               'font': {'size': 20}},
        number={'font': {'size': 48, 'color': COLORS['accent_1']}},
        domain={'x': [0, 1], 'y': [0.3, 1]}
    ),
    row=3, col=2
)

# ===== CHART 9: Data Table =====
fig.add_trace(
    go.Table(
        header=dict(
            values=['<b>AGE GROUP</b>', '<b>POPULATION</b>', '<b>GROWTH %</b>'],
            fill_color=COLORS['surface_light'],
            font=dict(color=COLORS['text_primary'], size=12, family='Roboto'),
            align='center',
            height=30,
            line_color=COLORS['border']
        ),
        cells=dict(
            values=[df['Age Group'],
                   [f"{p}M" for p in df['Population (Millions)']],
                   [f"{g}%" for g in df['Growth_Trend']]],
            fill_color=COLORS['surface'],
            font=dict(color=COLORS['text_secondary'], size=11),
            align='center',
            height=28,
            line_color=COLORS['border']
        )
    ),
    row=3, col=3
)

# ===== MASTER LAYOUT =====
fig.update_layout(
    title={
        'text': (
            "<b style='font-size:32px; letter-spacing:2px'>INDIA POPULATION ANALYTICS</b><br>"
            "<span style='font-size:14px; color:#B0B8D4; letter-spacing:1px'>INTERACTIVE DEMOGRAPHIC INTELLIGENCE DASHBOARD • 2022</span>"
        ),
        'y': 0.985,
        'x': 0.5,
        'xanchor': 'center',
        'yanchor': 'top',
        'font': {'color': COLORS['text_primary'], 'family': 'Roboto, Arial'}
    },

    paper_bgcolor=COLORS['bg_primary'],
    plot_bgcolor=COLORS['bg_secondary'],

    font=dict(family='Roboto, Arial, sans-serif', size=11, color=COLORS['text_secondary']),

    hoverlabel=dict(
        bgcolor=COLORS['surface'],
        font_size=12,
        font_family="Roboto",
        bordercolor=COLORS['accent_1'],
        font_color=COLORS['text_primary']
    ),

    showlegend=True,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=-0.08,
        xanchor="center",
        x=0.5,
        bgcolor=COLORS['surface'],
        bordercolor=COLORS['border'],
        borderwidth=1,
        font=dict(size=10, color=COLORS['text_primary'])
    ),

    height=1400,
    width=1800,

    margin=dict(t=120, b=100, l=60, r=60)
)

# Update all axes
fig.update_xaxes(
    showgrid=True,
    gridwidth=0.5,
    gridcolor=COLORS['grid'],
    showline=True,
    linewidth=1,
    linecolor=COLORS['border'],
    tickfont=dict(size=10, color=COLORS['text_secondary']),
    title_font=dict(size=11, color=COLORS['text_primary'])
)

fig.update_yaxes(
    showgrid=True,
    gridwidth=0.5,
    gridcolor=COLORS['grid'],
    showline=True,
    linewidth=1,
    linecolor=COLORS['border'],
    tickfont=dict(size=10, color=COLORS['text_secondary']),
    title_font=dict(size=11, color=COLORS['text_primary'])
)

# Specific axis labels
fig.update_xaxes(title_text="AGE GROUPS", row=1, col=1)
fig.update_yaxes(title_text="POPULATION (M)", row=1, col=1)

fig.update_xaxes(title_text="YEAR", row=1, col=2)
fig.update_yaxes(title_text="POPULATION (M)", row=1, col=2)

fig.update_xaxes(title_text="YEAR", row=2, col=1)
fig.update_yaxes(title_text="PROJECTED (M)", row=2, col=1)

fig.update_xaxes(title_text="DENSITY %", row=3, col=1)

# Update subplot titles
for i, annotation in enumerate(fig['layout']['annotations']):
    if i < 9:  # Only subplot titles
        annotation['font'] = dict(
            size=12,
            color=COLORS['accent_1'],
            family='Roboto',
            weight='bold'
        )
        annotation['y'] = annotation['y'] + 0.015

# Add corner badges
corner_annotations = [
    dict(
        text="<b>MEDIAN AGE</b><br>28 YEARS",
        xref="paper", yref="paper",
        x=0.01, y=0.99,
        xanchor='left', yanchor='top',
        showarrow=False,
        font=dict(size=10, color=COLORS['text_primary'], family='Roboto'),
        bgcolor=COLORS['surface_light'],
        borderpad=8,
        borderwidth=1,
        bordercolor=COLORS['accent_1'],
        opacity=0.95
    ),
    dict(
        text="<b>GLOBAL RANK</b><br>#1 POPULOUS",
        xref="paper", yref="paper",
        x=0.99, y=0.99,
        xanchor='right', yanchor='top',
        showarrow=False,
        font=dict(size=10, color=COLORS['text_primary'], family='Roboto'),
        bgcolor=COLORS['surface_light'],
        borderpad=8,
        borderwidth=1,
        bordercolor=COLORS['accent_2'],
        opacity=0.95
    ),
    dict(
        text="<b>DATA SOURCE</b><br>CENSUS 2022",
        xref="paper", yref="paper",
        x=0.01, y=0.01,
        xanchor='left', yanchor='bottom',
        showarrow=False,
        font=dict(size=9, color=COLORS['text_secondary'], family='Roboto'),
        bgcolor=COLORS['surface'],
        borderpad=6,
        borderwidth=1,
        bordercolor=COLORS['grid'],
        opacity=0.9
    )
]

fig.update_layout(annotations=list(fig['layout']['annotations']) + corner_annotations)

# Display
fig.show()

# Save
fig.write_html("india_population_hightech_dashboard.html")
print("✓ HIGH-TECH DASHBOARD CREATED")
print("→ File: india_population_hightech_dashboard.html")

try:
    fig.write_image("india_population_hightech_dashboard.png", scale=2)
    print("✓ PNG EXPORTED")
except:
    print("⚠ Install kaleido for PNG export")